version: '3'

services:

  db:
    image: "postgres:alpine"
    container_name: db
    volumes:
      - queue-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  game-queue-server:
    build: .
    container_name: auth-app

    environment:
      DB_SERVER: db
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 8081:8081
    links:
      - db
    depends_on:
      - db

volumes:
  queue-data: