server:
  port: 8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1

  jpa:
    generate-ddl: true
    hibernate:
        ddl-auto: create
        default_schema: auth
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  private:
    key: classpath:rsa.private.key
  public:
    key: classpath:rsa.public.key

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    enabled: true
    path: /rest-api-docs